import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/Navbar'
import { inriaSerif, poppins } from '@/utils/font'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inriaSerif.className} ${poppins.className}  antialiased`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  )
}
